### PR TITLE
items service folder deleted

### PR DESCRIPTION
**Pull request by alex-a-renoire**

### CODE REVIEW

**Comment by DrIhor** [comment]
Delete `pkg/grpc/server.go `file too.
Also there may be some other.

**Comment by stasBigunenko** [comment]
I think we will delete old GRPC files server and storage from the project, after confirming all new services and storages

**Comment by alex-a-renoire** [comment]
> I think we will delete old GRPC files server and storage from the project, after confirming all new services and storages

Sure, as soon as you will change cmd/grpc

**Comment by alex-a-renoire** [comment]
> pkg/grpc/server.go

I think i checked and there are no others. We will delete pkg/grpc/server.go together with pkg/grpc folder as soon as all changes are merged (right not if i delete pkg/grpc) some errors occur.

**Comment by DrIhor** [comment]
My comment is about empty files. Just check is you need them.

**Review by DrIhor — APPROVED** [review]

**Pull request merged**
