### PR TITLE
directory structure added

### PR DESCRIPTION
**Pull request by alex-a-renoire**
Issue #16

### CODE REVIEW

**Review by DrIhor — COMMENTED** [review]
Can you remove root main file???

**Review by DrIhor — COMMENTED** [review]
And can you add storage part???

**Review by DrIhor — APPROVED** [review]

**Review by stasBigunenko — APPROVED** [review]

**Comment by romanilchyshyn** [comment]
It would be great to pass CI check. It fails because no packages in directory found. That was a reason for adding `main.go`. 

For now just add package names inside added `*.go` files or at least one.

**Comment by romanilchyshyn** [comment]
Also remember to move [card](https://github.com/stasBigunenko/monorepa/projects/2#card-68438022) into `In progress` state when start working on issue.

**Comment by romanilchyshyn** [comment]
Also, you can mention issue number (like this #16) in description and|or PR title to logically bind issue and PR.

**Comment by romanilchyshyn** [comment]
@stasBigunenko @DrIhor I'd ask you guys do the same when working on issues.

Fun fact. If you mention issue number inside commit message like this 
Screenshot 2021-09-09 at 15 47 42
it would be easier in future to track the task you was working on and context of changes.

**Comment by romanilchyshyn** [comment]
What makes me happy the most 😌😌😌
green-ci

**Review by romanilchyshyn — APPROVED** [review]
LGTM. But still need to add layout info into #16

**Pull request merged**
